# Base configs
baseurl: "https://floppypocket.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Johnny Gainer"
subtitle: "The punctum is a spectre"
author: "Johnny Gainer"
header:
 title: "Photography"
 subtitle: "by Johnny Gainer"
footer:
 name: "Hey there, my name is Johnny"
 bio: "I am a ghost."

